version: '3.8'

services:

  backend:
    build: ./
    ports:
      - "8080:8080"  
    environment:
      Database_URL: mongodb+srv://Ali:InfraGroupe5BDD@clusterprojetinfra.hkin23h.mongodb.net/?retryWrites=true&w=majority
      Database: pandemic
      
      
