package modele.actions;

public enum TypeAction {
    VOITUREOUTRANSBORDEUR("VOITURE OU TRANSBORDEUR"),
    NAVETTE("NAVETTE"),
    VOLCHARTEUR("VOL CHARTEUR"),
    VOLDIRECT("VOL DIRECT"),
    PARTAGERCONNAISSANCES("PARTAGER CONNAISSANCES"),
    DECOUVRIRREMEDE("DECOUVRIR REMEDE"),
    TRAITERMALADIE("TRAITER UNE MALADIE"),
    CONSTRUIRESTATIONRECHERCHE("CONSTRUIRE UNE STATION DE RECHERCHE"),
    REPLACER_JOUEUR_VERS_AUTRE_JOUEUR("DEPLACER UN JOUR SUR UNE VILLE QUI CONTIENT UN AUTRE JOUEUR"),
    DEPLACER_JOUEUR_SUR_UNE_VILLE("DEPLACER UN JOUR SUR UNE VILLE");


    private String nomAction ;

    TypeAction(String nomEvenement) {
        this.nomAction = nomAction ;
    }

    public String getNomAction() {
        return nomAction;
    }
}
